(() => {
  const S = (id, name, set, year, names) => ({
    id,
    name,
    set,
    year,
    archive: true,
    licensed: true,
    scannable: false,
    manualOnly: true,
    noRemotePhoto: true,
    figures: names.map((pair, i) => ({
      id: `${id}-${i + 1}`,
      number: i + 1,
      name: pair[0],
      name_en: pair[1],
      codes: [],
      noRemotePhoto: true
    }))
  });

  const specials = [
    S('team-gb', 'Team GB 8909', '8909', 2012, [
      ['Boxeur puissant','Brawny Boxer'],
      ['Nageuse furtive','Stealth Swimmer'],
      ['Coureur de relais','Relay Runner'],
      ['Judoka','Judo Fighter'],
      ['Joueuse de tennis tactique','Tactical Tennis Player'],
      ['Gymnaste flexible','Flexible Gymnast'],
      ['Haltérophile prodigieux','Wondrous Weightlifter'],
      ['Cavalière','Horseback Rider'],
      ['Archer agile','Agile Archer']
    ]),

    S('lego-movie-1', 'La Grande Aventure LEGO 71004', '71004', 2014, [
      ['Calamity Drone','Calamity Drone'],
      ['Président Business','President Business'],
      ['Emmet avec casque de chantier','Hard Hat Emmet'],
      ['Wyldstyle Far West','Wild West Wyldstyle'],
      ['Abraham Lincoln','Abraham Lincoln'],
      ['Mme Scratchen-Post','Mrs. Scratchen-Post'],
      ['Bad Cop au visage gribouillé','Scribble-Face Bad Cop'],
      ['William Shakespeare','William Shakespeare'],
      ['Gail, ouvrière du bâtiment','Gail the Construction Worker'],
      ['Larry le barista','Larry the Barista'],
      ['Velma Staplebot','Velma Staplebot'],
      ['Homme Taco Tuesday','Taco Tuesday Guy'],
      ['Homme « Où est mon pantalon ? »','Where Are My Pants? Guy'],
      ['Wiley Fusebot','Wiley Fusebot'],
      ['Homme panda','Panda Guy'],
      ['Marsha, reine des sirènes','Marsha Queen of the Mermaids']
    ]),

    S('simpsons-1', 'Les Simpson 71005', '71005', 2014, [
      ['Homer Simpson','Homer Simpson'],
      ['Bart Simpson','Bart Simpson'],
      ['Marge Simpson','Marge Simpson'],
      ['Lisa Simpson','Lisa Simpson'],
      ['Maggie Simpson','Maggie Simpson'],
      ['Abraham « Grandpa » Simpson','Abraham Grandpa Simpson'],
      ['Ned Flanders','Ned Flanders'],
      ['Krusty le clown','Krusty the Clown'],
      ['Milhouse Van Houten','Milhouse Van Houten'],
      ['Ralph Wiggum','Ralph Wiggum'],
      ['Apu Nahasapeemapetilon','Apu Nahasapeemapetilon'],
      ['Nelson Muntz','Nelson Muntz'],
      ['Itchy','Itchy'],
      ['Scratchy','Scratchy'],
      ['Chef Clancy Wiggum','Chief Clancy Wiggum'],
      ['Charles Montgomery Burns','Charles Montgomery Burns']
    ]),

    S('simpsons-2', 'Les Simpson Série 2 71009', '71009', 2015, [
      ['Homer Simpson','Homer Simpson'],
      ['Marge Simpson','Marge Simpson'],
      ['Lisa Simpson','Lisa Simpson'],
      ['Maggie Simpson','Maggie Simpson'],
      ['Bart Simpson','Bart Simpson'],
      ['Milhouse Van Houten','Milhouse Van Houten'],
      ['Comic Book Guy','Comic Book Guy'],
      ['Martin Prince','Martin Prince'],
      ['Professeur Frink','Professor Frink'],
      ['Hans Moleman','Hans Moleman'],
      ['Selma Bouvier','Selma Bouvier'],
      ['Patty Bouvier','Patty Bouvier'],
      ['Groundskeeper Willie','Groundskeeper Willie'],
      ['Edna Krabappel','Edna Krabappel'],
      ['Waylon Smithers','Waylon Smithers'],
      ['Dr Julius Hibbert','Dr Julius Hibbert']
    ]),

    S('disney-1', 'Disney Série 1 71012', '71012', 2016, [
      ['Stitch','Stitch'],
      ['Alien','Alien'],
      ['Buzz Lightyear','Buzz Lightyear'],
      ['Aladdin','Aladdin'],
      ['Génie','Genie'],
      ['Maléfique','Maleficent'],
      ['Alice','Alice'],
      ['Chat du Cheshire','Cheshire Cat'],
      ['Daisy Duck','Daisy Duck'],
      ['Donald Duck','Donald Duck'],
      ['Minnie Mouse','Minnie Mouse'],
      ['Mickey Mouse','Mickey Mouse'],
      ['M. Indestructible','Mr. Incredible'],
      ['Syndrome','Syndrome'],
      ['Peter Pan','Peter Pan'],
      ['Capitaine Crochet','Captain Hook'],
      ['Ursula','Ursula'],
      ['Ariel','Ariel']
    ]),

    S('dfb', 'Équipe d’Allemagne DFB 71014', '71014', 2016, [
      ['Joachim Löw','Joachim Löw'],
      ['Manuel Neuer','Manuel Neuer'],
      ['Jérôme Boateng','Jérôme Boateng'],
      ['Mats Hummels','Mats Hummels'],
      ['Benedikt Höwedes','Benedikt Höwedes'],
      ['Shkodran Mustafi','Shkodran Mustafi'],
      ['Bastian Schweinsteiger','Bastian Schweinsteiger'],
      ['Mesut Özil','Mesut Özil'],
      ['Thomas Müller','Thomas Müller'],
      ['Mario Götze','Mario Götze'],
      ['Christoph Kramer','Christoph Kramer'],
      ['Sami Khedira','Sami Khedira'],
      ['Marco Reus','Marco Reus'],
      ['André Schürrle','André Schürrle'],
      ['Max Kruse','Max Kruse'],
      ['Toni Kroos','Toni Kroos']
    ]),

    S('lego-batman-1', 'LEGO Batman Le Film 71017', '71017', 2017, [
      ['Batman amateur de homards','Lobster-Lovin’ Batman'],
      ['L’Effaceur','The Eraser'],
      ['Le Maître Zodiac','Zodiac Master'],
      ['Roi Tut','King Tut'],
      ['Batgirl Pink Power','Pink Power Batgirl'],
      ['Dick Grayson','Dick Grayson'],
      ['Orca','Orca'],
      ['Fairy Batman','Fairy Batman'],
      ['Batman Glam Metal','Glam Metal Batman'],
      ['Batman homme des cavernes','Clan of the Cave Batman'],
      ['Batman en vacances','Vacation Batman'],
      ['Le Joker à l’asile d’Arkham','Arkham Asylum Joker'],
      ['La Calculette','The Calculator'],
      ['Red Hood','Red Hood'],
      ['Commissaire Gordon','Commissioner Gordon'],
      ['Barbara Gordon','Barbara Gordon'],
      ['March Harriet','March Harriet'],
      ['Le Mime','The Mime'],
      ['Catman','Catman'],
      ['Infirmière Harley Quinn','Nurse Harley Quinn']
    ]),

    S('ninjago-movie', 'LEGO NINJAGO Le Film 71019', '71019', 2017, [
      ['Kai Kendo','Kai Kendo'],
      ['Nya entraînement Spinjitzu','Spinjitzu Training Nya'],
      ['Lloyd','Lloyd'],
      ['Jay Walker','Jay Walker'],
      ['Cole','Cole'],
      ['Zane','Zane'],
      ['Lloyd Garmadon','Lloyd Garmadon'],
      ['Maître Wu','Master Wu'],
      ['Maître sushi','Sushi Chef'],
      ['Fille N-POP','N-POP Girl'],
      ['Technicienne GPL','GPL Tech'],
      ['Pieuvre de l’armée des requins','Shark Army Octopus'],
      ['Grand requin blanc de l’armée des requins','Shark Army Great White'],
      ['Général n°1 de l’armée des requins','Shark Army General #1'],
      ['Angler de l’armée des requins','Shark Army Angler'],
      ['Garmadon','Garmadon'],
      ['Garmadon du volcan','Volcano Garmadon'],
      ['Garmadon du passé','Flashback Garmadon'],
      ['Misako','Misako'],
      ['Rockeur gong et guitare','Gong & Guitar Rocker']
    ]),

    S('lego-batman-2', 'LEGO Batman Le Film Série 2 71020', '71020', 2018, [
      ['Batman en maillot de bain','Swimsuit Batman'],
      ['Robin en vacances','Vacation Robin'],
      ['Le Joker en vacances','Vacation The Joker'],
      ['Harley Quinn disco','Disco Harley Quinn'],
      ['Alfred Pennyworth en vacances','Vacation Alfred Pennyworth'],
      ['Batgirl en vacances','Vacation Batgirl'],
      ['Docteur Phosphorus','Doctor Phosphorus'],
      ['Le Roi du Temps','Clock King'],
      ['Batman sirène','Mermaid Batman'],
      ['Killer Moth','Killer Moth'],
      ['Jor-El','Jor-El'],
      ['Général Zod','General Zod'],
      ['Apache Chief','Apache Chief'],
      ['Batgirl Bat-Merch','Bat-Merch Batgirl'],
      ['Hugo Strange','Hugo Strange'],
      ['Alfred Pennyworth disco','Disco Alfred Pennyworth'],
      ['Black Canary','Black Canary'],
      ['Black Vulcan','Black Vulcan'],
      ['Wonder Twin Zan','Wonder Twin Zan'],
      ['Wonder Twin Jayna','Wonder Twin Jayna']
    ]),

    S('harry-potter-1', 'Harry Potter & Les Animaux fantastiques 71022', '71022', 2018, [
      ['Norbert Dragonneau','Newt Scamander'],
      ['Jacob Kowalski','Jacob Kowalski'],
      ['Tina Goldstein','Tina Goldstein'],
      ['Queenie Goldstein','Queenie Goldstein'],
      ['Crédence Bellebosse','Credence Barebone'],
      ['Luna Lovegood','Luna Lovegood'],
      ['Neville Londubat','Neville Longbottom'],
      ['Cho Chang','Cho Chang'],
      ['Dean Thomas','Dean Thomas'],
      ['Lord Voldemort','Lord Voldemort'],
      ['Dobby','Dobby'],
      ['Cedric Diggory','Cedric Diggory'],
      ['Alastor Maugrey « Fol Œil »','Mad-Eye Moody'],
      ['Professeur Flitwick','Professor Flitwick'],
      ['Professeure Trelawney','Professor Trelawney'],
      ['Albus Dumbledore','Albus Dumbledore'],
      ['Harry Potter en uniforme','Harry Potter in School Robes'],
      ['Ron Weasley en uniforme','Ron Weasley in School Robes'],
      ['Hermione Granger en uniforme','Hermione Granger in School Robes'],
      ['Drago Malefoy','Draco Malfoy'],
      ['Harry Potter en pyjama','Harry Potter in Pajamas'],
      ['Percival Graves','Percival Graves']
    ]),

    S('lego-movie-2', 'La Grande Aventure LEGO 2 71023', '71023', 2019, [
      ['Emmet Remix génial','Awesome Remix Emmet'],
      ['Lucy prête au combat','Battle-Ready Lucy'],
      ['Apocalypse Benny','Apocalypse Benny'],
      ['Homme girafe','Giraffe Guy'],
      ['Fille crayon','Crayon Girl'],
      ['Sherry Scratchen-Post & Scarfield','Sherry Scratchen-Post & Scarfield'],
      ['Hula Lula','Hula Lula'],
      ['Homme pastèque','Watermelon Dude'],
      ['Lucy Flashback','Flashback Lucy'],
      ['Créature des marais','The Swamp Creature'],
      ['Candy Rapper','Candy Rapper'],
      ['Président Business au golf','Gone Golfin’ President Business'],
      ['Apocalypseburg Abe','Apocalypseburg Abe'],
      ['Vest Friend Rex','Vest Friend Rex'],
      ['Kitty Pop','Kitty Pop'],
      ['Dorothy Gale & Toto','Dorothy Gale & Toto'],
      ['Lion peureux','Cowardly Lion'],
      ['Épouvantail','Scarecrow'],
      ['Homme de fer-blanc','Tin Man'],
      ['Unikitty','Unikitty']
    ]),

    S('disney-2', 'Disney Série 2 71024', '71024', 2019, [
      ['Mickey Mouse classique','Mickey Mouse'],
      ['Minnie Mouse classique','Minnie Mouse'],
      ['Picsou','Scrooge McDuck'],
      ['Riri','Huey'],
      ['Fifi','Dewey'],
      ['Loulou','Louie'],
      ['Tic','Chip'],
      ['Tac','Dale'],
      ['Elsa','Elsa'],
      ['Anna','Anna'],
      ['Jafar','Jafar'],
      ['Jasmine','Jasmine'],
      ['Hadès','Hades'],
      ['Hercule','Hercules'],
      ['Sally','Sally'],
      ['Jack Skellington','Jack Skellington'],
      ['Edna Mode','Edna Mode'],
      ['Frozone','Frozone']
    ]),

    S('dc-super-heroes', 'DC Super Heroes 71026', '71026', 2020, [
      ['Mister Miracle','Mister Miracle'],
      ['Wonder Woman','Wonder Woman'],
      ['Aquaman','Aquaman'],
      ['Stargirl','Star Girl'],
      ['Sinestro','Sinestro'],
      ['Cheetah','Cheetah'],
      ['Superman','Superman'],
      ['Green Lantern','Green Lantern'],
      ['Cyborg','Cyborg'],
      ['Batman','Batman'],
      ['Huntress','Huntress'],
      ['Metamorpho','Metamorpho'],
      ['Le Joker','The Joker'],
      ['Bumblebee','Bumblebee'],
      ['Jay Garrick Flash','Jay Garrick Flash'],
      ['Bat-Mite','Bat-Mite']
    ]),

    S('harry-potter-2', 'Harry Potter Série 2 71028', '71028', 2020, [
      ['Harry Potter','Harry Potter'],
      ['Albus Dumbledore','Albus Dumbledore'],
      ['Hermione Granger','Hermione Granger'],
      ['Ron Weasley','Ron Weasley'],
      ['Luna Lovegood','Luna Lovegood'],
      ['Gripsec','Griphook'],
      ['Lily Potter','Lily Potter'],
      ['James Potter','James Potter'],
      ['Ginny Weasley','Ginny Weasley'],
      ['Fred Weasley','Fred Weasley'],
      ['George Weasley','George Weasley'],
      ['Bellatrix Lestrange','Bellatrix Lestrange'],
      ['Kingsley Shacklebolt','Kingsley Shacklebolt'],
      ['Mimi Geignarde','Moaning Myrtle'],
      ['Professeure Pomona Chourave','Professor Pomona Sprout'],
      ['Neville Londubat','Neville Longbottom']
    ]),

    S('looney-tunes', 'Looney Tunes 71030', '71030', 2021, [
      ['Lola Bunny','Lola Bunny'],
      ['Bugs Bunny','Bugs Bunny'],
      ['Vil Coyote','Wile E. Coyote'],
      ['Bip Bip','Road Runner'],
      ['Titi','Tweety Bird'],
      ['Grosminet','Sylvester'],
      ['Daffy Duck','Daffy Duck'],
      ['Speedy Gonzales','Speedy Gonzales'],
      ['Taz','Tasmanian Devil'],
      ['Marvin le Martien','Marvin the Martian'],
      ['Pétunia Pig','Petunia Pig'],
      ['Porky Pig','Porky Pig']
    ]),

    S('marvel-1', 'Marvel Studios 71031', '71031', 2021, [
      ['Scarlet Witch','Scarlet Witch'],
      ['Vision','Vision'],
      ['Monica Rambeau','Monica Rambeau'],
      ['Winter Soldier','Winter Soldier'],
      ['Captain America (Sam Wilson)','Captain America (Sam Wilson)'],
      ['Loki','Loki'],
      ['Sylvie','Sylvie'],
      ['Spider-Man','Spider-Man'],
      ['Captain Carter','Captain Carter'],
      ['Star-Lord (T’Challa)','Star-Lord (T’Challa)'],
      ['Gamora','Gamora'],
      ['Zombie Captain America','Zombie Captain America']
    ]),

    S('muppets', 'Les Muppets 71033', '71033', 2022, [
      ['Rowlf','Rowlf the Dog'],
      ['Dr Bunsen Honeydew','Dr. Bunsen Honeydew'],
      ['Beaker','Beaker'],
      ['Gonzo','Gonzo'],
      ['Kermit la grenouille','Kermit the Frog'],
      ['Miss Piggy','Miss Piggy'],
      ['Fozzie Bear','Fozzie Bear'],
      ['Animal','Animal'],
      ['Chef suédois','Swedish Chef'],
      ['Waldorf','Waldorf'],
      ['Statler','Statler'],
      ['Janice','Janice']
    ]),

    S('disney-100', 'Disney 100 71038', '71038', 2023, [
      ['Oswald le lapin chanceux','Oswald the Lucky Rabbit'],
      ['Pinocchio','Pinocchio'],
      ['Jiminy Cricket','Jiminy Cricket'],
      ['Mickey apprenti sorcier','Mickey Mouse'],
      ['Tiana','Tiana'],
      ['Dr Facilier','Dr. Facilier'],
      ['Reine de Cœur','Queen of Hearts'],
      ['Aurore','Aurora'],
      ['Mulan','Mulan'],
      ['Ernesto de la Cruz','Ernesto de la Cruz'],
      ['Miguel Rivera','Miguel Rivera'],
      ['Pocahontas','Pocahontas'],
      ['Cruella d’Enfer','Cruella de Vil'],
      ['Robin des Bois','Robin Hood'],
      ['Prince Jean','Prince John'],
      ['Stitch','Stitch'],
      ['Baymax','Baymax'],
      ['Méchante Reine','Evil Queen']
    ]),

    S('marvel-2', 'Marvel Studios Série 2 71039', '71039', 2023, [
      ['Agatha Harkness','Agatha Harkness'],
      ['Moon Knight','Moon Knight'],
      ['Mr. Knight','Mr. Knight'],
      ['Werewolf by Night','Werewolf by Night'],
      ['She-Hulk','She-Hulk'],
      ['Hawkeye','Hawkeye'],
      ['Kate Bishop','Kate Bishop'],
      ['Goliath','Goliath'],
      ['Echo','Echo'],
      ['Beast','Beast'],
      ['Storm','Storm'],
      ['Wolverine','Wolverine']
    ])
  ];

  const existing = Array.isArray(window.MINIFIG_DATA) ? window.MINIFIG_DATA : [];
  const specialIds = new Set(specials.map(series => series.id));
  const merged = [...existing.filter(series => !specialIds.has(series.id)), ...specials];

  // Toutes les séries, numérotées ou sous licence, sont présentées des plus récentes aux plus anciennes.
  // Le tri natif est stable : l’ordre déjà défini reste inchangé entre séries d’une même année.
  merged.sort((a, b) => (Number(b.year) || 0) - (Number(a.year) || 0));
  window.MINIFIG_DATA = merged;
})();
